comment:
  layout: header, changes, diff, sunburst
coverage:
  precision: 0
  round: down
  range: "30...80"
  ignore:
  - GroupLockiOS/GroupLockTests/*
  status:
    patch:
      default:
        target: auto
    project:
      default:
        target: auto
