
matrix:
  include:
# For iOS builds:
  - language: swift
    os: osx
    osx_image: xcode8
    env: DEVICE="iPhone 4s" VERSION=10.0 TARGET="iOS"
  - language: swift
    os: osx
    osx_image: xcode8
    env: DEVICE="iPhone 5s" VERSION=10.0 TARGET="iOS"
  - language: swift
    os: osx
    osx_image: xcode8
    env: DEVICE="iPhone 6s" VERSION=10.0 TARGET="iOS"
  - language: swift
    os: osx
    osx_image: xcode8
    env: DEVICE="iPhone 6s Plus" VERSION=10.0 TARGET="iOS"

before_install:
  - if [[ $TARGET == "iOS" ]] ; then rvm use 2.2; fi
  - if [[ $TARGET == "iOS" ]] ; then sudo gem install xcpretty --no-rdoc --no-ri --no-document; fi
  - if [[ $TARGET == "iOS" ]] ; then sudo gem install cocoapods --no-rdoc --no-ri; fi
  - if [[ $TARGET == "iOS" ]] ; then pod install --project-directory=GroupLockiOS --repo-update; fi

script:
  - if [[ $TARGET == "iOS" ]] ; then set -o pipefail && xcodebuild -workspace GroupLockiOS/GroupLock.xcworkspace -scheme GroupLock -destination "platform=iOS Simulator,name=$DEVICE,OS=$VERSION" build test | xcpretty; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
