osx_image: xcode8.1

matrix:
  include:
# For iOS builds:
  - language: swift
    os: osx
    env: TARGET="iOS" SDK="iphonesimulator10.1" DEVICE="iPhone SE" VERSION=10.0
  - language: swift
    os: osx
    env: TARGET="iOS" SDK="iphonesimulator10.1" DEVICE="iPhone 5s" VERSION=10.0
  - language: swift
    os: osx
    env: TARGET="iOS" SDK="iphonesimulator10.1" DEVICE="iPhone 6s" VERSION=10.0
  - language: swift
    os: osx
    env: TARGET="iOS" SDK="iphonesimulator10.1" DEVICE="iPhone 6s Plus" VERSION=10.0
  - language: swift
    os: osx
    env: TARGET="iOS" SDK="iphonesimulator10.1" DEVICE="iPhone 7" VERSION=10.1
  - language: swift
    os: osx
    env: TARGET="iOS" SDK="iphonesimulator10.1" DEVICE="iPhone 7 Plus" VERSION=10.1
# For C/C++ library builds:
  - language: cpp
    os: osx
    compiler: clang
    env: TARGET="Lib"
  - language: cpp
    os: linux
    compiler: gcc
    env: TARGET="Lib"

before_install:
  - if [[ $TARGET == "iOS" ]] ; then
      gem install cocoapods --no-rdoc --no-ri;
      pod install --project-directory=GroupLockiOS --repo-update;
    fi

script:
  - if [[ $TARGET == "iOS" ]] ; then
      set -o pipefail && xcodebuild build test -workspace GroupLockiOS/GroupLock.xcworkspace -scheme GroupLock -sdk $SDK -destination "OS=$VERSION,name=$DEVICE" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      sleep 10;
      set -o pipefail && xcodebuild test -workspace GroupLockiOS/GroupLock.xcworkspace -scheme GroupLock -sdk $SDK -destination "OS=$VERSION,name=$DEVICE" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]] ; then
      brew install cmake;
    fi
  - if [[ $TARGET == "Lib" ]] ; then
      cd GroupLockCrypto/Build && cmake .. && make;
      ./glcrypto_TestRunner;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
