osx_image: xcode8.1

matrix:
  include:
# For iOS builds:
  - language: swift
    os: osx
    env: DEVICE="iPhone SE" VERSION=10.0 TARGET="iOS"
  - language: swift
    os: osx
    env: DEVICE="iPhone 5s" VERSION=10.0 TARGET="iOS"
  - language: swift
    os: osx
    env: DEVICE="iPhone 6s" VERSION=10.0 TARGET="iOS"
  - language: swift
    os: osx
    env: DEVICE="iPhone 6s Plus" VERSION=10.0 TARGET="iOS"
  - language: swift
    os: osx
    env: DEVICE="iPhone 7" VERSION=10.1 TARGET="iOS"
  - language: swift
    os: osx
    env: DEVICE="iPhone 7 Plus" VERSION=10.1 TARGET="iOS"
# For C/C++ library builds:
  - language: cpp
    os: osx
    compiler: clang
    env: TARGET="Lib"

before_install:
  - if [[ $TARGET == "iOS" ]] ; then
      rvm use 2.2;
      sudo gem install xcpretty --no-rdoc --no-ri --no-document;
      sudo gem install cocoapods --no-rdoc --no-ri;
      pod install --project-directory=GroupLockiOS --repo-update;
    fi

script:
  - if [[ $TARGET == "iOS" ]] ; then
      set -o pipefail && xcodebuild -workspace GroupLockiOS/GroupLock.xcworkspace -scheme GroupLock -destination "platform=iOS Simulator,name=$DEVICE,OS=$VERSION" build test | xcpretty; fi
  - if [[ $TARGET == "Lib" ]] ; then
      cd GroupLockCrypto/Build && cmake .. && make;
      ./glcrypto_TestRunner;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
